import { Metadata } from 'next'
import { ServicePageTemplate } from '@/components/service-page-template'
import { Battery } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Solar Battery Installation Victoria | Home Battery Storage',
  description: 'Premium solar battery installation services across Victoria. Store excess solar energy, reduce grid dependence, and enjoy backup power. Tesla Powerwall, BYD, and more. Get your free quote today.',
  keywords: [
    'solar battery installation',
    'home battery storage',
    'Tesla Powerwall Victoria',
    'solar battery cost',
    'battery storage systems',
    'energy storage',
    'backup power',
    'off-grid solar',
  ],
  openGraph: {
    title: 'Solar Battery Installation Victoria | Home Battery Storage',
    description: 'Store excess solar energy and achieve energy independence with premium battery systems in Victoria. Get your free quote today.',
    url: 'https://vrjelectrics.com.au/solar-battery-installation',
  },
}

const serviceData = {
  icon: Battery,
  title: 'Solar Battery Installation',
  subtitle: 'Battery Storage',
  description: 'Achieve true energy independence with our premium solar battery installation service. Store excess solar energy during the day and use it at night, reducing your grid dependence and protecting against power outages.',
  heroStats: [
    { value: '80%', label: 'Grid Independence' },
    { value: '10+', label: 'Year Warranty' },
    { value: '$3K', label: 'Avg Savings/Year' },
  ],
  detailedDescription: [
    'Solar batteries are revolutionising the way Victorians use energy. By storing excess power generated by your solar panels during the day, you can use clean, free energy even when the sun goes down. This means significantly reduced electricity bills and greater energy independence.',
    'Our team specialises in installing premium battery systems from leading manufacturers including Tesla Powerwall, BYD, SolarEdge, and Enphase. We carefully assess your energy usage patterns to recommend the optimal battery size that maximises your investment.',
    'Beyond cost savings, a solar battery provides peace of mind during power outages. With backup functionality, your essential appliances keep running when the grid goes down. This is particularly valuable in areas prone to storms or bushfires.',
  ],
  benefits: [
    {
      title: 'Energy Independence',
      description: 'Reduce your reliance on the grid by up to 80%. Use your own stored solar power day and night.',
    },
    {
      title: 'Backup Power',
      description: 'Keep your lights on and appliances running during grid outages. Essential for Victorian conditions.',
    },
    {
      title: 'Maximise Solar Investment',
      description: 'Use all the solar power you generate instead of selling excess back to the grid at low feed-in rates.',
    },
    {
      title: 'Peak Rate Protection',
      description: 'Avoid expensive peak electricity rates by using stored solar power during high-tariff periods.',
    },
    {
      title: 'Future-Proof Your Home',
      description: 'Prepare for time-of-use tariffs and EV charging with intelligent battery management systems.',
    },
    {
      title: 'Reduce Carbon Footprint',
      description: 'Maximise your use of clean, renewable energy and minimise your environmental impact.',
    },
  ],
  process: [
    {
      title: 'Energy Assessment',
      description: 'We analyse your energy usage patterns to determine the optimal battery size.',
    },
    {
      title: 'System Design',
      description: 'Our engineers design a battery solution that integrates perfectly with your solar system.',
    },
    {
      title: 'Professional Installation',
      description: 'CEC-accredited installers complete the installation safely and efficiently.',
    },
    {
      title: 'System Activation',
      description: 'We configure your system for optimal performance and show you how to monitor it.',
    },
  ],
  rebates: {
    title: 'Battery Rebates & Incentives',
    items: [
      'Victorian Battery Rebate: Up to $2,950 for eligible households',
      'Solar Victoria Interest-free Battery Loans',
      'Federal Small-scale Technology Certificates (STCs)',
      'Virtual Power Plant (VPP) programs for ongoing credits',
    ],
    note: 'Rebate availability varies by state and is subject to eligibility criteria. Our team will identify all rebates you qualify for.',
  },
  faqs: [
    {
      question: 'How much does a solar battery cost in Victoria?',
      answer: 'Solar battery prices range from $8,000 to $15,000+ depending on capacity. A popular 10kWh battery like the Tesla Powerwall costs around $12,000-$14,000 installed. With available rebates, you could save $2,000-$4,000 off these prices.',
    },
    {
      question: 'How long do solar batteries last?',
      answer: 'Quality solar batteries typically last 10-15 years with warranties of 10+ years. Most batteries are warranted to retain 70-80% of their capacity after 10 years of use.',
    },
    {
      question: 'Can I add a battery to my existing solar system?',
      answer: 'Yes! Most existing solar systems can have a battery added. The process involves assessing your current inverter and potentially adding a hybrid inverter or AC-coupled battery system.',
    },
    {
      question: 'What size battery do I need?',
      answer: 'The ideal battery size depends on your energy usage and goals. Most homes benefit from a 10-13kWh battery, which can cover evening and overnight usage for an average household.',
    },
    {
      question: 'Do batteries work during blackouts?',
      answer: 'Yes, but only if your system is configured for backup. We install batteries with automatic backup switching to keep essential circuits running during grid outages.',
    },
  ],
  heroImage: '/solar-battery-banner.png',
}

export default function SolarBatteryInstallationPage() {
  return <ServicePageTemplate {...serviceData} />
}
